version: '3.8'
services:
  crawler:
    build:
      context: ./crawler/
      dockerfile: Dockerfile
    volumes:
      - json_data:/app/json
    # container_name: kurumi-crawler
    # ports:
    #   - 59001:59001
    # environment:
    #   - NODE_ENV: development
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    volumes:
      - json_data:/app/json
volumes:
  json_data:
